package com.eldercare.common.enums;

public enum AbnormalType {
    SERVICE_TIMEOUT,
    TEMP_REASSIGN,
    NO_CHECKOUT,
    FAMILY_REJECTED,
    QUALIFICATION_MISMATCH,
    ELDER_PAUSED,
    NO_CHECKIN,
    AREA_MISMATCH,
    TIME_CONFLICT,
    CONTINUOUS_HOURS_EXCEEDED,
    RISK_LEVEL_MISMATCH,
    CHECKIN_ABNORMAL,
    FALL_RISK,
    COMPLAINT,
    INSURANCE_REPORT,
    SUPPLEMENT_ORDER,
    NURSE_LEAVE,
    CONTRAINDICATION_MISMATCH,
    TEMP_ADD_ITEM,
    OTHER
}
