import request from '@/utils/request'

export const getElders = () => request.get('/elders')
export const getElder = (id) => request.get(`/elders/${id}`)
export const getEldersByStatus = (status) => request.get(`/elders/status/${status}`)
export const searchElders = (name) => request.get(`/elders/search`, { params: { name } })
export const createElder = (data) => request.post('/elders', data)
export const updateElder = (id, data) => request.put(`/elders/${id}`, data)
export const suspendElder = (id, reason) => request.post(`/elders/${id}/suspend`, { reason })
export const resumeElder = (id) => request.post(`/elders/${id}/resume`)
export const deleteElder = (id) => request.delete(`/elders/${id}`)

export const getCaregivers = () => request.get('/caregivers')
export const getActiveCaregivers = () => request.get('/caregivers/active')
export const getCaregiver = (id) => request.get(`/caregivers/${id}`)
export const getMatchedCaregivers = (qualifications, serviceType) =>
  request.get('/caregivers/matched', { params: { qualifications, serviceType } })
export const checkCaregiverQualification = (caregiverId, requiredQualifications) =>
  request.post('/caregivers/check-qualification', { caregiverId, requiredQualifications })
export const createCaregiver = (data) => request.post('/caregivers', data)
export const updateCaregiver = (id, data) => request.put(`/caregivers/${id}`, data)
export const deleteCaregiver = (id) => request.delete(`/caregivers/${id}`)

export const getDemands = () => request.get('/demands')
export const getDemand = (id) => request.get(`/demands/${id}`)
export const getDemandsByStatus = (status) => request.get(`/demands/status/${status}`)
export const getDemandsByElder = (elderId) => request.get(`/demands/elder/${elderId}`)
export const createDemand = (data) => request.post('/demands', data)
export const updateDemand = (id, data) => request.put(`/demands/${id}`, data)
export const cancelDemand = (id, reason) => request.post(`/demands/${id}/cancel`, { reason })
export const deleteDemand = (id) => request.delete(`/demands/${id}`)

export const getWorkOrders = () => request.get('/workorders')
export const getWorkOrder = (id) => request.get(`/workorders/${id}`)
export const getWorkOrdersByDemand = (demandId) => request.get(`/workorders/demand/${demandId}`)
export const getWorkOrdersByCaregiver = (caregiverId) => request.get(`/workorders/caregiver/${caregiverId}`)
export const getWorkOrdersByStatus = (status) => request.get(`/workorders/status/${status}`)
export const dispatchWorkOrder = (data) => request.post('/workorders/dispatch', data)
export const updateWorkOrderStatus = (id, orderStatus) => request.put(`/workorders/${id}/status`, { orderStatus })

export const getCheckIns = () => request.get('/checkins')
export const getCheckIn = (id) => request.get(`/checkins/${id}`)
export const getCheckInsByWorkOrder = (workOrderId) => request.get(`/checkins/workorder/${workOrderId}`)
export const getLatestCheckIn = (workOrderId) => request.get(`/checkins/workorder/${workOrderId}/latest`)
export const hasCheckedIn = (workOrderId) => request.get(`/checkins/workorder/${workOrderId}/exists`)
export const doCheckIn = (data) => request.post('/checkins/checkin', data)
export const doCheckOut = (id, data) => request.post(`/checkins/${id}/checkout`, data)
export const updateCheckIn = (id, data) => request.put(`/checkins/${id}`, data)

export const getSettlements = () => request.get('/settlements')
export const getSettlement = (id) => request.get(`/settlements/${id}`)
export const getSettlementsByStatus = (status) => request.get(`/settlements/status/${status}`)
export const getSettlementsByWorkOrder = (workOrderId) => request.get(`/settlements/workorder/${workOrderId}`)
export const createSettlement = (data) => request.post('/settlements/create', data)
export const confirmSettlement = (id, operator) => request.post(`/settlements/${id}/confirm`, { operator })
export const cancelSettlement = (id, reason) => request.post(`/settlements/${id}/cancel`, { reason })
